version: '3'
services:

  mongodb:
    image: mongo
    ports:
    - 27017:27017

  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/app
    depends_on:
    - mongodb
    env_file:
    - .env

  postgresdb:
    image: postgres
    ports:
    - "5556:5432"
    env_file:
      - .env

  etl:
    build: etl_job/
    volumes:
    - ./etl_job/:/app
    depends_on:
    - mongodb
    - postgres
    env_file:
    - .env

  slackbot:
    build: slackbot/
    volumes:
    - ./slackbot/:/app
    depends_on:
    - postgresdb
    env_file:
    - .env